name: Waka Readme

on:
  push:
    branches: [master]
  schedule:
    - cron: "1 0 * * *":
jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: ulisesgopa/ulisesgopa@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: "master"
          COMMIT_MSG: "Automated Coding Activity Update :alien:"

          STATS_RANGE: "last_7_days"